version: '3'
services:
  redisedge:
    build:
      context: ./redisedge
      dockerfile: Dockerfile.jetson
    ports:
      - 6379:6379
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  init:
    build:
      context: ./app
      dockerfile: Dockerfile.jetson
    depends_on:
      - redisedge
    command: ['init.py', '--url', 'redis://redisedge:6379', '--device', 'GPU']
  server:
    build:
      context: ./app
      dockerfile: Dockerfile.jetson
    depends_on:
      - init
    ports:
      - 5000:5000
    command: ['server.py', '--url', 'redis://redisedge:6379']
  capture:
    build:
      context: ./app
      dockerfile: Dockerfile.jetson
    depends_on:
      - init
    # To capture from a webcam, uncomment the next lines
    # devices:
    #  - /dev/video0:/dev/video0
    # command: ['capture.py', '--url', 'redis://redisedge:6379']
    command: ['capture.py', '--url', 'redis://redisedge:6379', 'data/countvoncount.mp4']
  
  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090
  prometheus-redistimeseries-adapter:
    image: redisfab/prometheus-redistimeseries-adapter:master-arm64v8-alpine
    # TODO: freeze version
    depends_on:
      - prometheus
    ports:
      - 9201:9201
    command: ['-redis-address', 'redisedge:6379', '-web.listen-address', '0.0.0.0:9201']
  grafana:
    build: ./grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
